import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import TopBar from "../components/TopBar.js"
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import Landing from "@/components/Landing.js";


// Misc
import { useAccount } from 'wagmi'



export default function Home() {
	const router = useRouter()
	const { address, isConnecting, isDisconnected } = useAccount()
	
	useEffect(() => {
		if (address) {
		  router.push('/dashboard')
		}
	  }, [address])

	if (isConnecting) return <div>Connecting…</div>

	return (
		<>
			<Head>
				<title>ETHLisbon</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header>
			<TopBar />
			</header>
			<main>
				{
					<Landing />
				}
			</main>
		</>
	);
}
